### PR TITLE
Refactor webservice endpoints for clairity

### PR DESCRIPTION
**Pull request by mjoss17**

### CODE REVIEW

**Comment by rnathuji** [comment]
@mjoss17 - Just FYI I changed the target branch for this PR to `next-release`.

**Comment by mjoss17** [comment]
@rnathuji there were two methods that I still could not figure out how to account for in local_raisecli - `context_course` and `context_system` - [Examples online](https://github.com/moodle/moodle/blob/f8eb36373db5e1cef14c0919f40b9d3f03b53670/enrol/meta/tests/privacy/provider_test.php) wanted simply a '\' before them like `\context_system` or a `use context_system`. These however are used in namespaced test files... our situation is a little different. I need to stop banging my head against this for a bit.

**Comment by rnathuji** [comment]
@mjoss17 - Are you referring to these errors:

```
1) enrolment_test::test_enable_self_enrolment_method_without_capabilities
Failed asserting that exception of type "Error" matches expected exception "required_capability_exception". Message was: "Class 'local_raisecli\external\context_course' not found" at
/home/runner/work/moodle-local_raisecli/moodle-local_raisecli/moodle/local/raisecli/classes/external/enrolment.php:68
/home/runner/work/moodle-local_raisecli/moodle-local_raisecli/moodle/local/raisecli/tests/enrolment_test.php:88
/home/runner/work/moodle-local_raisecli/moodle-local_raisecli/moodle/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///home/runner/work/moodle-local_raisecli/moodle-local_raisecli/moodle/vendor/phpunit/phpunit/phpunit:97
```

If so, it looks to me like the errors are coming from `entrolment.php` and not `enrolment_test.php`. Probably all of the references in the former need to be explicitly tied to the root namespace by adding `\` in places like [here](https://github.com/openstax/moodle-local_raisecli/blob/455f1fc7d0ef0e75da6ce5ac326b7fc91e0f01ae/classes/external/enrolment.php#L68).

**Comment by mjoss17** [comment]
@rnathuji I just checked again, and I was definitely trying this with no success - what happens then for the enrolment tests is I get a `Error: Class "local_raisecli\external\context_course` error for the 3/5 tests that contain that `context_course` class and method. The remaining two tests fail with the `Failed asserting that exception of type "Error" matches expected exception "required_capability_exception". Message was: "Class "local_raisecli\external\context_course" not found"`

**Review by rnathuji — APPROVED** [review]

**Pull request merged**
